version: "2"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
  api:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      PORT: 3000 
